import type { Metadata } from "next";
import "./globals.css";
import ContactSection from "../components/layout/ContactSection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className="bg-black">
      <body className="h-screen w-full">
        {children}
        <ContactSection />
      </body>
    </html>
  );
}
